# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2208d263d567aa0374e4ee8a025127bf74bc3f162e88e624b551d314c8d802ff15425d1dc89c1de3ea85bdaf83def1fe31e306807feba77f0f6f9ed96755a607

test:
  secret_key_base: 426e16d03dfd3c1307fd9e6f83318c8c2161518307a09d6b62c3ca5705907b856f50517014cff7467fd3ac48b27a8574234be671cbc32ab603f8b75e2b4d7111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
